// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3K04loWkjgad7hEbjwXYpOmgCBN-qKbM',
    appId: '1:360230062506:web:0effe030eeec7542edc3d3',
    messagingSenderId: '360230062506',
    projectId: 'myheart-38164',
    authDomain: 'myheart-38164.firebaseapp.com',
    storageBucket: 'myheart-38164.firebasestorage.app',
    measurementId: 'G-1NRRCX4X9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPcUS-ZoJAPD5IG-1WAiemiuaVf04ZS84',
    appId: '1:360230062506:android:c96252a74ac98dbdedc3d3',
    messagingSenderId: '360230062506',
    projectId: 'myheart-38164',
    storageBucket: 'myheart-38164.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qwgfONxhq8tesB2OgfXxcg_uoVU-m7M',
    appId: '1:360230062506:ios:aa14c714e5fd10dfedc3d3',
    messagingSenderId: '360230062506',
    projectId: 'myheart-38164',
    storageBucket: 'myheart-38164.firebasestorage.app',
    iosBundleId: 'com.example.giamsatSuckhoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qwgfONxhq8tesB2OgfXxcg_uoVU-m7M',
    appId: '1:360230062506:ios:aa14c714e5fd10dfedc3d3',
    messagingSenderId: '360230062506',
    projectId: 'myheart-38164',
    storageBucket: 'myheart-38164.firebasestorage.app',
    iosBundleId: 'com.example.giamsatSuckhoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3K04loWkjgad7hEbjwXYpOmgCBN-qKbM',
    appId: '1:360230062506:web:de581a0bbf5731d5edc3d3',
    messagingSenderId: '360230062506',
    projectId: 'myheart-38164',
    authDomain: 'myheart-38164.firebaseapp.com',
    storageBucket: 'myheart-38164.firebasestorage.app',
    measurementId: 'G-837VV4G06S',
  );

}